#!/bin/bash

django_admim=$BINDIR/django-admin.py
project_dir=$PWD/.project
fixtures=$PWD/test/fixtures

mkdir -p $project_dir

cd $project_dir

DJANGO_SETTINGS_MODULE= $django_admim startproject project .

for app in app1 app2 jquery_app
do
    $django_admim startapp $app
    mkdir -p $project_dir/$app/static/$app
    mkdir -p $project_dir/$app/templates/$app
done

cp -f $fixtures/settings.py $project_dir/project/settings.py
cp -f $fixtures/app1.js $project_dir/app1/static/app1/app1.js
cp -f $fixtures/app2.js $project_dir/app2/static/app2/app2.js
cp -f $fixtures/app2.html $project_dir/app2/templates/app2/app2.html
cp -f $fixtures/jquery_app.html $project_dir/jquery_app/templates/jquery_app/jquery_app.html
