#!/bin/bash

django_admim=$BINDIR/django-admin.py
project_dir=$PWD/.project
fixtures=$PWD/test/fixtures

mkdir -p $project_dir

cd $project_dir

DJANGO_SETTINGS_MODULE= $django_admim startproject project .

for app in app1 app2
do
    $django_admim startapp $app
done

ln -f $fixtures/settings.py $project_dir/project/settings.py
