#!/bin/bash

django_admim=$BINDIR/django-admin.py
project_dir=$PWD/.project
fixtures=$PWD/test/fixtures

mkdir -p $project_dir

cd $project_dir

DJANGO_SETTINGS_MODULE= $django_admim startproject project .

for app in app1 app2
do
    $django_admim startapp $app
    mkdir -p $project_dir/$app/static
done

cp -f $fixtures/settings.py $project_dir/project/settings.py

mkdir -p $project_dir/app1/static/app1

cp -f $fixtures/app1.js $project_dir/app1/static/app1/app1.js

mkdir -p $project_dir/app2/templates/app2

cp -f $fixtures/app2.html $project_dir/app2/templates/app2/app2.html
